baseURL: https://beta.lecaros.info/
languageCode: en-us
title: lecaros.info
theme: hugo-theme-stack
params:
  contact:
    email: hola@lecaros.info
  subtitle: "A blog about software development, technology, and other stuff."
languages:
  en:
    contentDir: content
    weight: 0
    languageName: English
    params:
      default: true
  es:
    contentDir: content/es
    languageName: Español
    weight: 1