baseURL: https://bblog.lecaros.info/
languageCode: en-us
title: lecaros.info
theme: hugo-theme-stack
params:
  contact:
    email: hola@lecaros.info
  subtitle: "A blog about software development, technology, and other stuff."
languages:
  en:
    contentDir: content
    weight: 0
    languageName: English
    params:
      default: true
  es:
    contentDir: content/es
    languageName: Español
    weight: 1
menu:
  main:
    - name: Home
      pageRef: /
      weight: 1
      params:
        icon: "home"
    - name: About
      pageRef: /about/
      weight: 2
      params:
        icon: "user"
  social:
    - name: GitHub
      url: https://github.com/lecaros
      params:
        icon: "brand-github"
    - name: Twitter
      url: https://twitter.com/lecaros
      params:
        icon: "brand-twitter"

