name: Credly to Hugo importer
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: michaelcontento/credly2hugo-action@v1.0.1
              with:
                  username: lecaros
